version: '3.7'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '9432:5432'
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - sample_network  # Add service to the custom network
    
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    ports:
      - "6479:6379"
    networks:
      - sample_network

  app1:
    build: .
    depends_on:
      - db
      - redis
    environment:
      FLASK_RUN_PORT: 8097
    ports:
      - "8097:8097"
    networks:
      - sample_network  # Add service to the custom network

  app2:
    build: .
    depends_on:
      - db
      - redis
    environment:
      FLASK_RUN_PORT: 8097
    ports:
      - "8098:8097"
    networks:
      - sample_network  # Add service to the custom network

networks:
  sample_network:  # Define custom network
    driver: bridge